[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    "@aave/contracts=lib/aave-v3-core/contracts",
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
